### ISSUE TITLE
How to use presenter for some attributes?

### ISSUE THREAD

**Issue by dixitchopra** [prettus/l5-repository#19]
This is awesome. This repository has saved my lot of time. I have used your repo in my codebase. I am finding solution for the following issue.

Here is the url: http://prettus.local/posts?filter=id;title and I am also using PostTransformer(https://github.com/andersao/l5-repository/#fractal-presenter) and have passed Post class as an argument. Now, I am only looking for two columns i.e. Id and Title where as PostTransformer is returning me array with all the columns that are there in the transform method i.e. Id, Title and Content. Content is always Null. 

Any solution? Thanks.

**Comment by andersao** [comment]
Hi @dixitchopra,

When you use the Filter, the Model will only return the columns requested in the case, id and title. In PostTransformer if you are prepared to make the Model with all its attributes, and when the filter is activated, the other columns are not returned and so it comes as null.

I think that a solution would be to perform a check on your PostTransformer, and only display columns that are defined, or another solution would be to use the method toArray () of the Model.

Ex:

```php
use App\Post;
use League\Fractal\TransformerAbstract;

class PostTransformer extends TransformerAbstract
{
    public function transform(Post $post)
    {
    	$data = [];
    	
    	if( isset($post->id) )
    		$data['id'] = (int) $post->id;

    	if( isset($post->title) )
    		$data['title'] = $post->title;

		if( isset($post->text) )
    		$data['text'] = $post->text;

    	return $data;
    }
}
```

Ex 2:

```php
use App\Post;
use League\Fractal\TransformerAbstract;

class PostTransformer extends TransformerAbstract
{
    public function transform(Post $post)
    {
    	$avaliable = ['id','title','text'];
    	$data 	   = array_only($post->toArray(), $avaliable);
    	
    	return $data;
    }
}
```

I hope I help!

**Comment by dixitchopra** [comment]
I am using second option in my code. There are two issues here. 
1. How can I change the column name title to Name?
2. This won't work with 'With'. return $this->postRepository->with(['user'])->all(); I
 am getting only Post model columns and not User columns. Earlier it was working.

**Comment by andersao** [comment]
@dixitchopra I'll get a solution for you :)

**Comment by andersao** [comment]
@dixitchopra Are you still having problems?

**Comment by golinmarq** [comment]
@andersao did you find a solution to him? I'm interested to apply this

**Comment by hoseinz3** [comment]
@andersao i'm still having problems.
