### ISSUE TITLE
How to filter by a loaded relationship?

### ISSUE THREAD

**Issue by geraldbiggs** [prettus/l5-repository#27]
Hi, I love using your repository and am learning its nuances. I'm curious how you could draw this statement utilizing the repository:

$users = User::with(['posts' => function($query)
{
    $query->where('title', 'like', '%first%');

}])->get();

This example is drawn from the laravel docs. I'm looking at an entity with many relationships, and may need to filter from any given one.

Thank you

**Comment by henninghorn** [comment]
I would probably add a new method to your user repository.
