### ISSUE TITLE
Bug: criteria is not reset

### ISSUE THREAD

**Issue by dimsav** [prettus/l5-repository#29]
To reproduce the bug, call two times a public method using the same repository instance. Example:

```php

$repo = app('SomeRepo');

$item = $repo->findWhere(['id' => 1]); // This returns the item
$item = $repo->findWhere(['id' => 2]); // This returns nothing!

```

The second call is equivalent to: 

```php
Model::where('id, '=', 1)->where('id', '=', 2)->get();
```

Which returns nothing of course. 

To fix that, execute `$this->makeModel()` inside `applyCriteria()`.

Btw it would be very nice if you would add some tests. [Laracasts integrated](https://github.com/laracasts/Integrated/) would help a lot.

**Comment by andersao** [comment]
@dimsav Hello, sorry for the delay in responding. I will correct the problem;) 	Thanks for the tip, I will implement the tests.

**Comment by devmark** [comment]
+1

**Comment by andersao** [comment]
@dimsav @devmark Fixed. I apologize for the delay. Release version 2.0.12

**Comment by devmark** [comment]
thanks :)
