### ISSUE TITLE
Possible copy of your project

### ISSUE THREAD

**Issue by vluzrmos** [prettus/l5-repository#31]
https://github.com/Bosnadev/Repositories

**Comment by andersao** [comment]
@vluzrmos Yes, he was inspired in my project, and even wrote a great article about the Repository pattern. https://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/

I commented on the post stating that he had been inspired by my project, he confirmed and said he would put the credits, but did :(

**Comment by vluzrmos** [comment]
@Bosnadev please...

**Comment by MarlonEtiene** [comment]
@Bosnadev give the credits to @andersao please!

**Comment by mirzap** [comment]
@andersao I'm sorry I was pretty busy, I haven't update my blog in a month :) I've added credits in a readme ;)

**Comment by mirzap** [comment]
Article it self is updated ;)
http://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/#Credits

I had in plan part 3 of repository series. I've made quite change in your "request criteria queries", but currently I'm very busy to write about it :).

**Comment by andersao** [comment]
@mirzap Thanks man!
