### ISSUE TITLE
Verifying 'ownership' on domain model

### ISSUE THREAD

**Issue by syflipper** [prettus/l5-repository#32]
What's the easiest way using this package - while keeping the repositories structure in mind - to validate ownership of models? Without repositories I would add a new function to the model, something like below but I can't figure out what would be the most efficient reusable DRY construction for this structure.

```php
//Game.php
public function verifyOwnership(User $user)
{
    if ($this->user_id != $user->id){
        throw new Exception();
    }
    return true;
}
```

```php
//GamesController.php
public function show($id)
{
    try
    {
        $game = Game::find($id);
        $game->verifyOwnership(Auth::user());
        
        //more logic
    } catch (Exception $e) {
        throw $e;
    }
}
```

**Comment by andersao** [comment]
@syflipper

Well, the repository will you return a instantiates your model , then you could use this method without problems. If you are using a presenter , simply ignore the presenter using the skipPresenter () method.

Try this:

//GamesController.php
public function __construct(GameRepository $repository){
	$this->repository = $repository;
}

public function show($id)
{
    try
    {
        $game = $this->repository->skipPresenter(true)->find($id);
        $game->verifyOwnership(Auth::user());

        //more logic
    } catch (Exception $e) {
        throw $e;
    }
}

**Comment by syflipper** [comment]
Thanks for your answer @andersao. The problem is that I have to present the data after it gets verified again (API output). Any tips on doing that?

**Comment by andersao** [comment]
@syflipper

You can do this by creating a customized presentation. Thus it will extract your model information to be displayed in their API , at that time you can treat the information that is displayed . See the example below :

https://github.com/prettus/l5-repository#create-a-presenter

//GameTransformer.php
```php
use App\Post;
use League\Fractal\TransformerAbstract;

class GameTransformer extends TransformerAbstract
{
    public function transform(Game $game)
    {
        $data = [];
        $data = [
			'id'=>$game->id,
			'title'=>$game->title
        ];

        if( $game->verifyOwnership(Auth::user()) )
        {
			$data = array_merge($data,[
				'dataOnlyIfOwnership'=>$game->privateData,
				....
			]);
        }

        return $data;
    }
}
```
//GamePresenter.php
```php
use Prettus\Repository\Presenter\FractalPresenter;

class GamePresenter extends FractalPresenter {

    /**
     * Prepare data to present
     *
     * @return \League\Fractal\TransformerAbstract
     */
    public function getTransformer()
    {
        return new GameTransformer();
    }
}
```
//GameRepository.php
```php
use Prettus\Repository\Eloquent\BaseRepository;

class GameRepository extends BaseRepository {

    ...

    public function presenter()
    {
        return "YOUR_NAMESPACE\\GamePresenter";
    }
}
```

I hope this works for you

**Comment by syflipper** [comment]
@andersao 👍
