### ISSUE TITLE
Add a layer of caching?

### ISSUE THREAD

**Issue by irazasyed** [prettus/l5-repository#33]
How about a layer of caching ? Of course configurable to enable for all/only few, skip, on-demand with default time and specific to each?

Would make this package perfect in all around.

**Comment by andersao** [comment]
Hello @irazasyed,
I 'm working on it right now, I'm also the same need . Soon I will publish this feature . :)

**Comment by irazasyed** [comment]
Hi @andersao,

Awesome, Sounds good. Thanks :+1:

**Comment by andersao** [comment]
@irazasyed Cacheable Featura released today, feel free to suggest any improvement. ;)
https://github.com/prettus/l5-repository#cache

**Comment by irazasyed** [comment]
@andersao Thanks for the awesome work and time you've put on this! Looks quite easy to implement. Will give a try soon and let you know if i have any suggestions. Appreciate it :) :+1:
