### ISSUE TITLE
Relationships for Presenters and Transformers

### ISSUE THREAD

**Issue by ruchiaz** [prettus/l5-repository#37]
Eg: for simple scenario like Category has multiple products. When select all category with products how to pass two Models to transformers. Its take only one model. How we can implement this?

**Comment by ruchiaz** [comment]
Sorry my bad. Its seems we don't need bind model for "With" attributes. It comes along with the transform model.

**Comment by jonagoldman** [comment]
Hey @ruchiaz I am trying to get this to work and will appreciate if you can tell me how you fixed it.

Please take a loot at the issue I opened here: https://github.com/andersao/l5-repository/issues/101

I basically want to decide when to transform relationships.

Thanks.
