### ISSUE TITLE
findWhere problem

### ISSUE THREAD

**Issue by yazfield** [prettus/l5-repository#38]
Hello, i've discovered a minor bug when I've been trying something like this: 

```PHP
$repository->findWhere([ ['key', '=', 'value'] ]);
```

but it doesn't work because of this (**line 299 in BaseRepository.php**)
```PHP
if( is_array($value) )
{
    list($field, $condition, $value) = $value;
    $this->model = $this->model->where($field,$condition,$value);
}
```
In fact, in the given example, $field contains 'v', $condition contains 'a' and $value contains 'value'
i'm not sure if this is a PHP bug or not, we can see that PHP starts by assigning the last variable, so $value = $value[2] = 'value', then it uses the new $value so we get $condition = $value[1] = 'a' and $field = $value[0] = 'v'

it can be easily fixed just by using new variables like this

```PHP
if( is_array($value) )
{
    list($field, $condition, $val) = $value;
    $this->model = $this->model->where($field,$condition,$val);
}
```

Cheers :smile:

**Comment by andersao** [comment]
@yazfield Thanks for the feedback , I have done the fix :)
