### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Jeroen-G** [prettus/l5-repository#42]
What would be the best way to test repositories (with L5.1)?
Do you have tests for this package, I do see a phpunit configuration file.

**Comment by andersao** [comment]
Hello @Jeroen-G , unfortunately today I did not complete the tests. In early versions I had implemented the tests for some features, but with time I stopped creates them . But I intend to invest the time to stop creating tests for the project.

**Comment by Jeroen-G** [comment]
Great! Keep up the good work!

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by tucq88** [comment]
How about now @andersao? (Don't mean to rush, just asking :D) 
Maybe you can just add some sample tests & rules to follow, so we could implement tests ourself - without messing around this great package.
