### ISSUE TITLE
Composer requirements

### ISSUE THREAD

**Issue by Jeroen-G** [prettus/l5-repository#43]
I see you have in your `require-dev` double requirements for `illuminate/http`. Also, any requirements in `require` are also loaded in a dev environment, so requiring `illuminate/support` in `require-dev` is not necessary I believe.
Is it possible to make the validation optional? I'd like to use the default Laravel, but the `prettus/laravel-validation` is pulled in anyway. Perhaps it could be optional, so people who want to use it will pull it in themselves? Or am I being a bit selfish with this and are many using this way of validating?
A last question, why are `illuminate/http`, `illuminate/pagination` and `illuminate/database` only in the `require-dev`?

**Comment by andersao** [comment]
Hello @Jeroen-G You're right, my fault when he was developing the next release will pose as the optional prettus/validator and correct the dependencies . Thanks for the feedback .

**Comment by Jeroen-G** [comment]
You're welcome!

**Comment by andersao** [comment]
@Jeroen-G Released version 2.1.0
