### ISSUE TITLE
SoftDelete conditions bypassed via OR-clauses when multiple fields in fieldSearchable

### ISSUE THREAD

**Issue by LordHamwich** [prettus/l5-repository#47]
When using multiple fields in repository's $fieldSearchable, softDelete-conditions do not work.

The cause is fairly obvious. Example of somewhat broken scenario:

$fieldSearchable = ['name', 'email'];

SELECT id, name, email FROM registered_users WHERE deleted_at IS NULL AND name LIKE '%.com%' OR email LIKE '%.com%';

If the keyword hits any field after the first OR in the query, deleted_at IS NULL -condition (which is always the first condition in any Eloquent-based query) doesn't really do anything.

**Comment by andersao** [comment]
Hello @LordHamwich ,

Thanks for reporting . Already realized the correction and will be published next release.

**Comment by andersao** [comment]
Hello @LordHamwich

Fixed. Released in version 2.1.*

**Comment by LordHamwich** [comment]
Thank you, we really appreciate your quick response; this is essential package in our project. Kudos!
